### PR TITLE
Typo fixes, additional development instructions, and minor refactoring

### PR DESCRIPTION
**Pull request by derekkramer**
💻 Minor refactoring in FinalJeopardy.jsx
💻 Minor refactoring in Players.js
💻 Minor refactoring in Row.js
💻 Minor refactoring in Setup.js
💻 Minor refactoring in App.js
📝 Removed duplicated dependencies in package.json
📖 Fixed typos in README.md and added up to date development run instructions

### CODE REVIEW

**Comment by denvaar** [comment]
@derekkramer happy to merge your fixes after conflicts are resolved.

**Comment by derekkramer** [comment]
@denvaar Fixed all conflicts!

**Comment by denvaar** [comment]
sorry @derekkramer I screwed it up again

**Comment by derekkramer** [comment]
All good @denvaar, fixed the conflicts again!

**Comment by denvaar** [comment]
thank you

**Pull request merged**
